name: Compliance

on:
  pull_request:
    branches: [master, develop]

jobs:
  compliance:
    runs-on: ubuntu-latest
    env:
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      SEMREL_DEBUG: 1
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - run: npx zx scripts/release.mjs --ju https://paymentworld.atlassian.net/browse --dry-run

      - name: Lint Commits
        run: npx commitlint -f $BASE_SHA

      - name: Run Tests
        run: npm test
