name: Release

on:
  push:
    branches: [master, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - if: ${{ github.ref_name == 'master' }}
      run: echo "Release ${{ github.ref_name }}"

    - if: ${{ github.ref_name == 'develop' }}
      run: echo "Release ${{ github.ref_name }}"
