name: Release

on:
  push:
    branches: [master, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      SEMREL_DEBUG: 1
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - if: ${{ github.ref_name == 'master' }}
        name: Release Production
        run: npx zx scripts/release.mjs

      - if: ${{ github.ref_name == 'develop' }}
        name: Release Staging
        run: npx zx scripts/release.mjs -s staging -i 1.0.10
